queue_rules:
  - name: default
    conditions:
      - base=master
      - status-success="validate commits"
      - status-success="ubuntu"
      - status-success="macos"
      - status-success="coverage"
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@chaos/chaos-developers"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~=^\[*[Ww][Ii][Pp]
 
pull_request_rules:
  - name: rebase and merge when passing all checks
    conditions:
      - base=master
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@chaos/chaos-developers"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~=^\[*[Ww][Ii][Pp]
    actions:
      queue:
        name: default
        method: merge
        update_method: rebase
  - name: remove outdated approved reviews
    conditions:
      - author!=@chaos-developers
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
        message: |
          Approving reviews have been dismissed because this pull request
          was updated.
