#!/bin/sh
echo "Running libtoolize --automake --copy ... "
libtoolize --automake --copy 
echo "Running autoreconf --verbose --install -I config"
autoreconf --verbose --install -I config
echo "Cleaning up ..."
mv aclocal.m4 config/
rm -rf autom4te.cache
echo "Now run ./configure."
