/* 
 * $Id$ 
 *
 * Copyright (C) 2000 Regents of the University of California
 * See ./DISCLAIMER
 *
 * Eventually this file should be generated by GNU autoconf.  For now,
 * we use platform ifdefs.
 */

#ifndef _CONF_INCLUDED
#define _CONF_INCLUDED

/* These two are user-settable - see README */
#define HAVE_KRB4		0
#define HAVE_GENDERS		1

#ifdef __linux					/* RH 6.2 alpha,sparc,intel */
#define HAVE_PTHREAD_SIGMASK	1
#define HAVE_GETHOSTBYNAME_R	1
#define HAVE_STRERROR_R		1
#ifdef sparc
#endif

#elif _AIX					/* AIX 4.3 */
#define HAVE_SDRGETOBJECTS	1
#define HAVE_SIGTHREADMASK	1
#define HAVE_STRERROR		0

#elif defined(sparc) && !defined(__linux)	/* sunos 5.7 */
#define HAVE_GETHOSTBYNAME_R	1
#endif

/*
 * Default values.
 */
#ifndef HAVE_FCNTL_H
#define HAVE_FCNTL_H		1
#endif
#ifndef HAVE_STRINGS_H
#define HAVE_STRINGS_H		1
#endif
#ifndef HAVE_SYS_IOCTL_H
#define HAVE_SYS_IOCTL_H	1
#endif
#ifndef HAVE_SYS_TIME_H
#define HAVE_SYS_TIME_H		1
#endif
#ifndef HAVE_UNISTD_H
#define HAVE_UNISTD_H		1
#endif
#ifndef HAVE_SYS_WAIT_H
#define HAVE_SYS_WAIT_H		1
#endif
#ifndef HAVE_PTHREAD_H
#define HAVE_PTHREAD_H		1
#endif
#ifndef HAVE_PTHREAD_SIGMASK
#define HAVE_PTHREAD_SIGMASK	1
#endif
#ifndef HAVE_SIGTHREADMASK
#define HAVE_SIGTHREADMASK	0
#endif
#ifndef KRB4
#define KRB4			0
#endif
#ifndef HAVE_GETHOSTBYNAME_R
#define HAVE_GETHOSTBYNAME_R	0
#endif
#ifndef HAVE_STRERROR_R
#define HAVE_STRERROR_R		0
#endif
#ifndef HAVE_STRERROR
#define HAVE_STRERROR		0
#endif
#ifndef HAVE_SDRGETOBJECTS
#define HAVE_SDRGETOBJECTS	0
#endif
#ifndef HAVE_GENDERS
#define HAVE_GENDERS		0
#endif

#endif
