\." $Id$
.\"
.TH PDSH 1 "Release 1.3" "LLNL" "PDSH"
.SH NAME
pdcp \- copy files to groups of hosts in parallel
.SH SYNOPSIS
.B pdcp
.I "[-options] src [src2...] dest"
.br
.SH DESCRIPTION
.B pdsh
is a variant of the rcp(1) command.  Unlike rcp(1) which copies files to
a single remote host, pdcp(1) can copy files to multiple remote hosts in 
parallel.  Options are described in TARGET NODE LIST OPTIONS and OTHER OPTIONS 
below.
.LP
When pdcp receives SIGINT (ctrl-C), it lists the status of current threads.
A second SIGINT within one second terminates the program.

.SH TARGET NODE LIST OPTIONS
.I "-w host,host,..."
Target the specified nodes.  No spaces are allowed in the comma-separated
list.  Substituting the "-" character for the list causes the target nodes
to be read from stdin, one per line. The node list may also contain hostname
ranges of the form "host1-5" in place of single hostnames. By default, 
.B pdsh
will attempt to expand these ranges based upon a range operator of '-'. The
environment var PDSH_RANGE_OPERATOR may be set to an arbitrary character 
which will be used in place of '-'. (Setting this variable to "" will
effectively disable range expansion.) See also the -x and -X options 
for similar functionality on the command line.
.LP
.I "-x"
Do not attempt to expand hostname ranges passed via -w.
.LP 
.I "-X c"
Use character 'c' as a range operator when expanding hostname ranges.
.LP
.I "-a"
Target "all" nodes in the cluster.  If running on an SP, this means all
nodes in your partition.  On a non-SP with genders support, this is all nodes
listed in your genders file.  Otherwise, it is all nodes in your MPICH
node list (see FILES below).
.LP
.I "-v"
(SP ONLY) In combination with -a, eliminate nodes that the SDR thinks are down.
.LP
.I "-i"
(SP or genders ONLY) In combination with -a or -g, use alternate node names.
On the SP, this means use SDR initial_hostname instead of the default 
reliable_hostname.  On non-SP's with genders, you must have 
.I "altname" 
attributes defined for each node.
.LP
.I "-G"
(SP ONLY) In combination with -a, include all partitions.
.LP
.I "-g attribute"
(Genders ONLY) Target nodes that have the specified attribute.
.LP
If none of the above options are specified, the WCOLL environment variable
must point to a file that contains a list of nodes, one per line.  
.SH OTHER OPTIONS
.I "-r"
Copy recursively.
.LP
.I "-p"
Preserve modification time and modes.
.LP
.I "-q"
List option values and the target nodes and exit without action.
.LP
.I "-f number"
Set the maximum number of simultaneous remote copies.  The default is 64.
.LP
.I "-l user"
This option may be used to copy files as another user, subject to
authorization.  For BSD rcmd, this means the invoking user and system must
be listed in the user\'s .rhosts file (even for root).
.LP
.I "-t seconds"
Set the connect timeout.  Default is 5 seconds.  (This is in addition to
the socket-level timeout which may cause connect(2) to fail sooner)
.LP
.I "-k"
(Kerberos IV ONLY) Use kerberized rcmd (default for root).
.LP
.I "-R"
(Kerberos IV ONLY) Use BSD rcmd (default for non-root)
.LP
.I "-d"
Include more complete thread status when SIGINT is received, and display
connect and command time statistics on stderr when done.

.SH "FILES"
MPICH Machines file:  /usr/local/etc/machines
.br
SDR query command: /usr/lpp/ssp/bin/SDRGetObjects
.br
Genders query command: /usr/bin/nodeattr

.SH "ORIGIN"
Pdsh/pdcp was originally a rewrite of IBM dsh(1) by Jim Garlick
.br
<garlick@llnl.gov>
on LLNL's ASCI Blue-Pacific IBM SP system.  
It is now also used on Alpha Linux clusters at LLNL.

.SH "SEE ALSO"
rcp(1), pdsh(1)
