set pdsh "$objdir/pdsh"
set dshbak "$objdir/dshbak"

# This test suite is for version 1.6.  Other versions cause a failure.
set test "version"
spawn $pdsh -V
expect {
	-re "pdsh-1.6.*"		{ pass "$test" }
	eof				{ fail "$test" }
}

# gnats:35 pdsh does not properly display errors on AIX
set test "xstrerrorcat gnats:35"
spawn $pdsh -T 0
expect  {
	-re ".*PASS"			{ pass "$test" }
	-re ".*FAIL"			{ fail "$test" }
	-re ".*UNSUPPORTED"		{ unsupported "$test" }
	-re ".*unknown"			{ unsupported "$test" }
}

# gnats:36 dshbak -c doesn't show difference between mult length output
set test "dshbak -c gnats:36"
spawn $dshbak -c
send "foo1: bar\n"
send "foo2: bar\n"
send "foo1: baz\n"
send \004
expect {
	-re "foo1-2"			{ fail "$test" }
	eof	 			{ pass "$test" }
}
