set pdsh "$objdir/pdsh"

expect_after {
	timeout				{ unresolved "$test" }
	eof				{ unresolved "$test" }
}

# This is required for the following test to work but I have no idea
# why. Let's blame DejaGNU.
expect eof

set test "pdsh: version (if this fails beware that testsuite is outdated)"
spawn $pdsh -V
expect  {
	-re "pdsh-1.7.*"		{ pass "$test" }
	eof				{ fail "$test" }
}

set test "pdsh: xstrerrorcat obtains text for errnos (gnats:35)"
spawn $pdsh -T 0
expect  {
	-re ".*PASS"			{ pass "$test" }
	-re ".*FAIL"			{ fail "$test" }
	-re ".*UNSUPPORTED"		{ unsupported "$test" }
	-re ".*unknown"			{ unsupported "$test" }
}

set test "pdsh: hostname range expansion works"
spawn  $pdsh -qw foo\[0-3\],foo\[4-5\]
expect  {
	-re "foo\\\[0-5\\\]" 		{ pass "$test" }
	eof	 			{ fail "$test" }
}

set test "pdsh: hostname range expansion does not strip leading zeros"
spawn $pdsh -qw foo\[00-02\]
expect  {
	-re "foo\\\[00-02\\\]"		{ pass "$test" }
	eof	 			{ fail "$test" }
}

set test "pdsh: hostname range expansion handles mixed size suffixes"
spawn $pdsh -qw "foo\[9-11\]"
expect  {
	-re "foo\\\[9-11\\\]"		{ pass "$test" }
	eof	 			{ fail "$test" }
}

set test "pdsh: -x option works"
spawn $pdsh -qw foo\[9-11\] -x foo10
expect  {
	-re "foo\\\[9,11\\\]"		{ pass "$test" }
	eof	 			{ fail "$test" }
}

set test "pdsh: ranges can be embedded in wcoll files"
spawn $pdsh -qw-
send "foo\[9-11\]\n"
send \004
expect  {
	-re "foo\\\[9-11\\\]"		{ pass "$test" }
	eof	 			{ fail "$test" }
}
