.\" $Id$
.\"
.TH DSHBAK 1 "2011-02-26"
.SH NAME
dshbak \- format output from pdsh command

.SH SYNOPSIS
.B dshbak 
[\fIOPTION\fR]..

.SH DESCRIPTION
The \fBdshbak\fR program formats \fBpdsh\fR pdsh output for humans.
Output from each node is consolidated, the leading "\fInode:\fR" is
stripped, and a header block with the node name is added. If the \fI-c\fR
option is specified, nodes with identical output are not displayed twice;
instead, the header will contain a list of nodes. The list of nodes is
further compressed into node ranges if the node names have a numeric suffix.

.SH OPTIONS
.TP
.BI "-h"
Display a summary of command line options.
.TP
.BI "-c"
Do not display identical output from nodes twice. Instead, print
the list of nodes with matching output in the header block.
.TP
.BI "-d " DIR
Write consolidated node output to separate files in output
directory \fIDIR\fR. Any existing files will be overwritten.
.TP
.BI "-f"
With \fI-d\fR, force creation of specified \fIDIR\fR.


.SH "ORIGIN"
A rewrite of IBM dshbak(1) by Jim Garlick
.br
<garlick@llnl.gov>
on LLNL's ASCI Blue-Pacific IBM SP system.  

.SH "SEE ALSO"
.BR pdsh (1)
.PP
\fBhttp://pdsh.googlecode.com\fR
